sudo: required

services:
  - docker

before_install:
  - docker pull rsmmr/clang
  - docker build -t rigel/v0.1 .
  - docker images
  - docker ps -a

script: ls

branches:
  only:
  - master
  - travis